### ISSUE TITLE
No way to specify label class/size?

### ISSUE THREAD

**Issue by TheTechnoMan** [formers/former#442] opened 2015-02-05 19:38 UTC
Hey,

it seems like that there is still no way to set the label size. I need to do this with former:

```
<div class="form-group">
    <label class="col-md-3 control-label" for="test">
        Product Name
    </label>
    <div class="col-md-6">
        <input id="test" class="form-control" type="text"></input>
    </div>
</div>
```

But I am not able to do so. Is there a way to do that?

Thank you very much!

**Comment by TheTechnoMan** [comment] 2015-02-08 04:53
Anyone? :(

**Comment by samjaninf** [comment] 2015-02-13 20:29
I have kind of the same issue. Only thing I have found is this: https://github.com/Anahkiasen/former/issues/368

Other than that. No such luck.

**Comment by TheTechnoMan** [comment] 2015-02-14 14:55
I found that too, does not help at all unfortunately. It also looks like that this package is no longer be maintained, so back to manual forms then..

**Comment by TommyC81** [comment] 2015-02-15 18:54
This has been driving me nuts as well (assuming we're talking about the same issue), how do I adjust the classes that are automatically added to labels etc. The current behavior seems hardcoded (no config in userspace) and is messing up my designs following an update to the latest version of former.

**Comment by TheTechnoMan** [comment] 2015-02-16 03:57
Yeah. I'm pretty sure thought that this won't change, sadly. I just went back to manual forms, don't want to deal with this issues anymore.

**Comment by gbrock** [comment] 2015-02-18 18:30
The options for this seem to be in `/src/config/TwitterBootstrap3.php`.  You should be able to `php artisan config:publish anahkiasen/former` to move these configs into your own app's config directory, making them specific to your application and open to change.

**Comment by claar** [comment] 2015-03-04 18:41
Dupe of #209

**Closed by claar** 2015-03-04 18:41 UTC
