### ISSUE TITLE
FatalErrorException in FormerServiceProvider.php line 147

### ISSUE THREAD

**Issue by Bulmer** [formers/former#459] opened 2015-03-18 08:33 UTC
I'm getting the following error trying to get Former working with L5 (I've previously enjoyed Former with L4 for a few years!):
"FatalErrorException in FormerServiceProvider.php line 147:
Call to undefined method Illuminate\Config\Repository::package()"
I tried to call "php artisan config:publish anahkiasen/former" and get the same error:
"Call to undefined method Illuminate\Config\Repository::package()".
Is there something here i've missed?

**Comment by tortuetorche** [comment] 2015-03-18 12:00
You should use the 4.0 branch for Laravel 5.

`"anahkiasen/former": "~4.0.0",`

And in your `composer.json` file, add these two options:
```javascript
{
	// Previous options...
	"prefer-stable": true,
	"minimum-stability": "dev"
}
```

Here a complete `composer.json` sample:
```json
{
	"name": "laravel/laravel",
	"description": "The Laravel Framework.",
	"keywords": ["framework", "laravel"],
	"license": "MIT",
	"type": "project",
	"require": {
		"laravel/framework": "5.0.*",
		"anahkiasen/former": "~4.0.0",
		"graham-campbell/exceptions": "~1.0"
	},
	"require-dev": {
		"phpunit/phpunit": "~4.0",
		"phpspec/phpspec": "~2.1",
		"barryvdh/laravel-debugbar": "~2.0",
		"way/generators": "~3.0"
	},
	"autoload": {
		"classmap": [
			"database",
			"app/Http/Controllers"
		],
		"psr-4": {
			"App\\": "app/"
		}
	},
	"autoload-dev": {
		"classmap": [
			"tests/TestCase.php"
		]
	},
	"scripts": {
		"post-install-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-update-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-create-project-cmd": [
			"php -r \"copy('.env.example', '.env');\"",
			"php artisan key:generate"
		]
	},
	"config": {
		"preferred-install": "dist"
	},
	"prefer-stable": true,
	"minimum-stability": "dev"
}
```

Duplicate of #438

**Closed by tortuetorche** 2015-03-18 12:00 UTC
Labels: duplicate

**Comment by Bulmer** [comment] 2015-03-18 20:43
Thanks tortuetorche, that fixed it, however there seems to be an error on the "https://github.com/formers/former/wiki/Getting-started" page because I followed the instruction to use "composer require anahkiasen/former" and what I got was v3.5. What would be the composer command to install v4 straight up?
