### ISSUE TITLE
[Agnostic] Hidden input throws an exception when name contains a '['

### ISSUE THREAD

**Issue by Javier-Rotelli** [formers/former#478] opened 2015-05-21 20:03 UTC
I'm trying to generate a hidden input with a name that contains '[' and ']'
when rendering the view i get 
"Method Former\Form\Fields\Hidden::__toString() must not throw an exception"

removing them everything works

**Comment by mashpie** [comment] 2015-07-15 14:53
hey, just ran into same issue and found workaround in #243, adding empty value:

    ->value('');

**Comment by adriandmitroca** [comment] 2015-07-17 16:28
Well, what if you want bind a value to that field? In that case
`->value('')` does not work.

**Comment by claar** [comment] 2017-05-30 17:36
Dupe of #243

**Closed by claar** 2017-05-30 17:36 UTC
