### ISSUE TITLE
Using Former 4.0 in Lumen (Laravel 5.0 micro framework)

### ISSUE THREAD

**Issue by aromot** [formers/former#468] opened 2015-04-23 16:44 UTC
Hello,

I can't get Former 4.0 work with the Lumen framework (based on Laravel 5).

I put in a simple blade view the following code :
```
use Former\Facades\Former;

echo Former::open()->method('GET');
    echo Former::text('name')->required();
echo Former::close();
```
and I get the following error :
```
ErrorException in Container.php line 776:Class former does not exist (View: ...)
```
so I added the ServiceProvider to my *app.php* :
```
$app->register('Former\FormerServiceProvider');
```
and I get the following error :
```
Fatal error: Call to undefined method Illuminate\Config\Repository::package() in D:\...\vendor\anahkiasen\former\src\Former\FormerServiceProvider.php on line 147
```

I contacted Maxime Fabre who told me to submit this issue here as it seems to be a bug.

**Comment by claar** [comment] 2015-04-23 17:58
I'm guessing you aren't using the 4.0 (Laravel 5) branch of former, as I just tried that exact view with Lumen and it worked fine. Is this in your composer.json?

```
    "require": {
        "anahkiasen/former": "4.0.*@dev"
    },
```

**Comment by aromot** [comment] 2015-04-23 18:41
Yes, I'm using the 4.0 branch (it is indicated at the very beginning of my post).

**Comment by claar** [comment] 2015-04-23 18:44
Ah, missed that. Unfortunately, I can't reproduce this.

**Comment by aromot** [comment] 2015-04-23 18:45
>>  I can't reproduce this.
Indeed, you surely can't on Laravel 5, but give a try with Lumen (http://www.lumen.laravel.com)

**Comment by claar** [comment] 2015-04-23 18:46
I referenced Lumen in my post ;)

**Comment by aromot** [comment] 2015-04-24 07:15
I didn't mention above that I had changed the *add.php* file with what follows:
- I've uncommented $app->withFacades();
- I've uncommented $app->withEloquent();
and I'm using the following middleware:
```
 $app->middleware([
//      'Illuminate\Cookie\Middleware\EncryptCookies',
//      'Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse',
      'Illuminate\Session\Middleware\StartSession',
//      'Illuminate\View\Middleware\ShareErrorsFromSession',
//      'Laravel\Lumen\Http\Middleware\VerifyCsrfToken',
 ]);
```
I have the following error:
```
ErrorException in Container.php line 776:
Class former does not exist (View: D:\service\resources\views\test.blade.php)
```
I came back to the out of the box app.php... and it works!
When I use facades (uncommenting $app->withFacades(); in app.php), the problem occurs again.
It seems that the problem comes from there, don't you think?

**Comment by claar** [comment] 2015-04-25 18:50
From http://lumen.laravel.com/docs/introduction

Also, unlike Laravel, Lumen is not intended to be used with additional Laravel "packages" such as debug bars, CMS systems, etc.

I'll gladly accept pull requests to fix this, but I'm going to close this as won't fix until someone is willing to do the work on this.

**Closed by claar** 2015-04-25 18:50 UTC
