### ISSUE TITLE
Could I pass Former to array and then view it?

### ISSUE THREAD

**Issue by yuomtheara** [formers/former#329] opened 2014-06-01 03:32 UTC
I want to pass Former to array and then view it like
```php
// in view
$form = array(
Former::text(),
Former::text(),
Former::text(),
);

foreach($form as $value){
    echo $value.'<br>';
}
```
It have problem when check validator->fails(), by return duplicated of errors message in the text box nearly.
Please help me.

**Comment by claar** [comment] 2015-03-04 17:43
Dupe of #323

**Closed by claar** 2015-03-04 17:43 UTC
