### ISSUE TITLE
Current state with Bootstrap 3

### ISSUE THREAD

**Issue by bschooly** [formers/former#401] opened 2014-10-12 18:11 UTC
Hi, new to Former, Bootstrap, and Laravel,...

I've been using Former (devmaster) with Bootstrap 3 but having difficulty in getting everything styled (error messages weren't styled correctly, disabled fields weren't styled at all, field widths could not be set, etc.)

Then I happened upon a thread here and noticed I needed to set the framework to 'TwitterBootstrap3'. Doing that cleared up some things, but it caused the field labels to be placed to the left of the field, not above as before. How to restore what I had?

I saw mention elsewhere here about this issue but it is unclear if that was solved. Lastly how do I set the input field width?

Thanks for your help in advance.

Bill

**Comment by claar** [comment] 2015-03-04 18:24
Dupe of #209

**Closed by claar** 2015-03-04 18:24 UTC
