### ISSUE TITLE
Former::submit()->icon not rendered correctly

### ISSUE THREAD

**Issue by fuse-64** [formers/former#436] opened 2015-02-03 10:54 UTC
When using the nice method chaining like this
```
Former::large_primary_submit('my submit'])->icon('check')
```
Former mixes up icon's html in the value attribute of the button.
To fix this :
in Former\Form\Fields\Button class 
```
public function __construct(){
...
// Set correct element for the various button patterns
		switch ($type) {
			case 'button':
+           case 'submit':
+           case 'reset':
				$this->element       = 'button';
				$this->isSelfClosing = false;
				break;
..
}
```

**Comment by claar** [comment] 2015-02-03 15:05
Nice workaround. Unfortunately, changing the HTML output of submit buttons to use <button> instead of <input> would break existing applications.

**Comment by claar** [comment] 2015-03-04 18:37
Dupe of #406

**Closed by claar** 2015-03-04 18:37 UTC
