### ISSUE TITLE
Problem with regex validation

### ISSUE THREAD

**Issue by MercerAsian** [formers/former#366] opened 2014-08-28 16:19 UTC
I'm working with Former and noticed a problem

The rule separator, ' | ', is also the *or* operator for regex. This causes the evaluation of my regex rule to be cut short.
This code...
```
{{
    Former::open()
        ->rules(array(
            'phone' => 'required|match:/(\d{7}|\d{10})/'
        ));
}}
```
```
{{ Former::text('phone')->label('Phone'); }}
```

produces this html...
```
<div class="col-lg-10 col-sm-8">
    <input id="phone" class="form-control" type="text" name="phone" pattern="(\d{7}" required="true"></input>
    <span class="help-block">
        Ex. 4784722190
    </span>
</div>
```

As you can see, the pattern attribute is wrong, how can we fix this?

**Comment by claar** [comment] 2015-03-04 18:31
Dupe of #428

**Closed by claar** 2015-03-04 18:31 UTC
