### ISSUE TITLE
I still have problem when "I pass Former to array and then view it"

### ISSUE THREAD

**Issue by yuomtheara** [formers/former#331] opened 2014-06-03 07:23 UTC
I want to pass Former to array and then view it like
```php
// in view
$form = array(
Former::text(),
Former::text(),
Former::text(),
);

foreach($form as $value){
    echo $value.'<br>';
}
```
It have problem when check validator->fails(), by return duplicated of errors message in the text box nearly.
And then i get the solution like this:
```
You need to render the fields when you store then like that, call ->wrapAndRender() on each Former::text().
```
But i try, it don't work.
Please help me again

**Comment by claar** [comment] 2015-03-04 17:43
Dupe of #323

**Closed by claar** 2015-03-04 17:43 UTC
