### ISSUE TITLE
Support Bootstrap4

### ISSUE THREAD

**Issue by codeforfungit** [formers/former#576] opened 2018-10-09 05:33 UTC
To support bootstrap 4 which files need to modify.I mean  is it possible override existing bootstrap 3 

Thanks

**Comment by claar** [comment] 2018-10-24 21:47
Dupe of #564.

Bootstrap 4 support is now released in [4.1.8](https://github.com/formers/former/releases/tag/4.1.8) thanks to @bdewong. Please give it a try!

**Closed by claar** 2018-10-24 21:47 UTC
Labels: Duplicate
